### ISSUE TITLE
Add license to repository

### ISSUE THREAD

**Issue by spikeheap** [jch254/terraform-ecs-autoscale-alb#3]
Hi! Thanks for contributing this terraform setup – it's really helped me get up to speed with ECS and terraform. 

I would like to use the ECS cluster/instance code here, but I can't see a license on the repo or code. Without a license the default copyright laws apply, which means no-one can (or probably "should") use the code.

I have an affinity towards MIT, but there's a whole host of options: https://help.github.com/articles/licensing-a-repository/.

**Comment by jch254** [comment]
Sorry for the lateness with this mate just saw the issue. I've added an MIT licence.
